# Homework

In [1]:
import numpy as np

from torch import nn
import torch

### Number 1

In [112]:
conv_1 = nn.Conv1d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)
print(conv_1.weight.shape)
conv_1.weight = torch.nn.Parameter(torch.Tensor([[[-1, 1]]]))

s = torch.Tensor([2,4,1,8,2,3])
s = torch.reshape(s, [1, -1])

print(conv_1.weight)
print(s.shape, s)
# print(conv_1(torch.ones([1, 4])))
print(conv_1(s))

Parameter containing:
tensor([[[-1.,  1.]]], requires_grad=True)
torch.Size([1, 6]) tensor([[2., 4., 1., 8., 2., 3.]])
tensor([[ 2., -3.,  7., -6.,  1.]], grad_fn=<SqueezeBackward1>)


### Number 2

In [115]:
X = np.array([
    [3, 2, 3],
    [0, 1, 2],
    [1, 3, 2],
])

weight = np.array([
    [1, 0],
    [1, -1]
])

conv_2 = nn.Conv2d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)
print(conv_2.weight.shape)
conv_2.weight = torch.nn.Parameter(torch.Tensor(np.reshape(weight, [1, 1, 2, 2])))

X = torch.reshape(torch.Tensor(X), (1, 3, 3))

print(conv_2.weight)
print(X.shape, X)
# print(conv_1(torch.ones([1, 4])))
print(conv_2(X))

torch.Size([1, 1, 2, 2])
Parameter containing:
tensor([[[[ 1.,  0.],
          [ 1., -1.]]]], requires_grad=True)
torch.Size([1, 3, 3]) tensor([[[3., 2., 3.],
         [0., 1., 2.],
         [1., 3., 2.]]])
tensor([[[ 2.,  1.],
         [-2.,  2.]]], grad_fn=<SqueezeBackward1>)


### Number 7

In [121]:
X = torch.Tensor(np.array([
    [2, 3, 2, 4], 
    [6, 5, 5, 1], 
    [8, 9, 3, 4], 
    [7, 2, 1, 8], 
]).reshape(1, 4, 4))

pool_7 = nn.AvgPool2d(kernel_size=2, stride=2)
conv_3 = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=2, bias=False)

# print(pool_7(X))
# print(4*3*4*6.5)
print(X.shape)
print(conv_3(X).shape)

torch.Size([1, 4, 4])
torch.Size([1, 6, 6])


In [125]:
X = torch.Tensor(np.array([
    [2, 3, 2, 4], 
    [6, 5, 5, 1], 
    [8, 9, 3, 4], 
    [7, 2, 1, 8], 
]).reshape(1, 4, 4))

conv_layer = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=2, bias=False)

print("Before conv:", X.shape)
print("After conv: ", conv_layer(X).shape)
print(conv_layer(X))

Before conv: torch.Size([1, 4, 4])
After conv:  torch.Size([1, 6, 6])
tensor([[[ 0.2806,  0.8159,  0.8442,  0.9129,  0.7610, -0.0577],
         [ 0.3669,  1.1807,  0.6942, -0.5526, -0.3046, -0.9009],
         [-0.9146,  0.3617, -1.2771, -1.4064, -0.8030,  0.4119],
         [-2.7543, -3.1639, -3.5029, -2.0735,  1.5803, -0.8291],
         [-4.1113, -4.7876, -3.0966, -2.6018, -0.4670, -1.0818],
         [-2.1428, -1.9956,  0.5083, -2.3009, -1.4082,  1.3825]]],
       grad_fn=<SqueezeBackward1>)
